// Autogenerated from Pigeon (v26.1.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, omit_obvious_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}
bool _deepEquals(Object? a, Object? b) {
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
        .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    return a.length == b.length && a.entries.every((MapEntry<Object?, Object?> entry) =>
        (b as Map<Object?, Object?>).containsKey(entry.key) &&
        _deepEquals(entry.value, b[entry.key]));
  }
  return a == b;
}


/// ///////////////////////////////////////////////////////////////////////////////////////////////////////
/// ///////////////////////////////////////////////////////////////////////////////////////////////////////
enum MediaCommand {
  pause,
  play,
  stop,
  togglePlayPause,
  nextTrack,
  previousTrack,
  repeatMode,
  shuffleMode,
  playBackRate,
  seekBackward,
  seekForward,
  skipBackward,
  skipForward,
  position,
  rating,
  like,
  dislike,
  bookmark,
}

//////////////////////////////////////////////////////////////////////////////////////////////////////////
enum MediaRepeatType {
  none,
  one,
  all,
}

enum MediaShuffleType {
  none,
  items,
  collections,
}

/// ///////////////////////////////////////////////////////////////////////////////////////////////////////
/// ///////////////////////////////////////////////////////////////////////////////////////////////////////
class MediaItem {
  MediaItem({
    this.title,
    this.artist,
    this.artUri,
    this.position,
    this.duration,
    this.playing,
  });

  String? title;

  String? artist;

  String? artUri;

  double? position;

  double? duration;

  bool? playing;

  List<Object?> _toList() {
    return <Object?>[
      title,
      artist,
      artUri,
      position,
      duration,
      playing,
    ];
  }

  Object encode() {
    return _toList();  }

  static MediaItem decode(Object result) {
    result as List<Object?>;
    return MediaItem(
      title: result[0] as String?,
      artist: result[1] as String?,
      artUri: result[2] as String?,
      position: result[3] as double?,
      duration: result[4] as double?,
      playing: result[5] as bool?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! MediaItem || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

//////////////////////////////////////////////////////////////////////////////////////////////////////////
class MediaNotification {
  MediaNotification({
    required this.command,
    this.value,
  });

  MediaCommand command;

  Object? value;

  List<Object?> _toList() {
    return <Object?>[
      command,
      value,
    ];
  }

  Object encode() {
    return _toList();  }

  static MediaNotification decode(Object result) {
    result as List<Object?>;
    return MediaNotification(
      command: result[0]! as MediaCommand,
      value: result[1],
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! MediaNotification || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is MediaCommand) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is MediaRepeatType) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is MediaShuffleType) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    }    else if (value is MediaItem) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is MediaNotification) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        final value = readValue(buffer) as int?;
        return value == null ? null : MediaCommand.values[value];
      case 130: 
        final value = readValue(buffer) as int?;
        return value == null ? null : MediaRepeatType.values[value];
      case 131: 
        final value = readValue(buffer) as int?;
        return value == null ? null : MediaShuffleType.values[value];
      case 132: 
        return MediaItem.decode(readValue(buffer)!);
      case 133: 
        return MediaNotification.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// ///////////////////////////////////////////////////////////////////////////////////////////////////////
/// ///////////////////////////////////////////////////////////////////////////////////////////////////////
class MediaSessionProtocol {
  /// Constructor for [MediaSessionProtocol].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  MediaSessionProtocol({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<void> setMedia(MediaItem item) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.flutter_media_session.MediaSessionProtocol.setMedia$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[item]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> setActiveCommands(List<MediaCommand> commands) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.flutter_media_session.MediaSessionProtocol.setActiveCommands$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[commands]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }
}

/// //////////////////////////////////////////////////////////////////////////////////////////////////////
/// ///////////////////////////////////////////////////////////////////////////////////////////////////////
abstract class MediaCommandCenter {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void notification(MediaNotification notification);

  static void setUp(MediaCommandCenter? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.flutter_media_session.MediaCommandCenter.notification$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.flutter_media_session.MediaCommandCenter.notification was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final MediaNotification? arg_notification = (args[0] as MediaNotification?);
          assert(arg_notification != null,
              'Argument for dev.flutter.pigeon.flutter_media_session.MediaCommandCenter.notification was null, expected non-null MediaNotification.');
          try {
            api.notification(arg_notification!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
